# Generated by Django 2.2.5 on 2019-09-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190929_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
    ]
