# Generated by Django 2.2.5 on 2019-09-29 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0004_author_serie'),
        ('books', '0010_book_type_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='refers.Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='refers.Serie'),
            preserve_default=False,
        ),
    ]
