# Generated by Django 2.2.5 on 2019-10-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0005_authortest'),
        ('books', '0011_auto_20190930_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_test',
            field=models.ManyToManyField(to='refers.AuthorTest'),
        ),
    ]
