# Generated by Django 2.2.5 on 2019-10-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_author_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_test',
        ),
    ]
