# Generated by Django 2.2.5 on 2019-10-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='month',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
