# Generated by Django 2.2.5 on 2019-10-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0008_auto_20191011_1536'),
        ('books', '0016_auto_20191011_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='serie',
        ),
        migrations.AddField(
            model_name='book',
            name='serie',
            field=models.ManyToManyField(to='refers.Serie', verbose_name='Серия'),
        ),
    ]
