# Generated by Django 2.2.5 on 2019-10-16 16:58

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20191011_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.image_folder, verbose_name='Обложка'),
        ),
    ]
