# Generated by Django 2.2.5 on 2019-09-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
