# Generated by Django 2.2.5 on 2019-09-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0002_publishinghouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
