# Generated by Django 2.2.5 on 2019-10-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0004_author_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
