# Generated by Django 2.2.5 on 2019-10-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_book_author_test'),
        ('refers', '0005_authortest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorTest',
        ),
    ]
