# Generated by Django 2.2.5 on 2019-10-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0006_delete_authortest'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='descr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
