# Generated by Django 2.2.5 on 2019-10-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0009_auto_20191012_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='descr',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
