# Generated by Django 2.2.5 on 2019-10-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0010_auto_20191014_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='descr',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='publishinghouse',
            name='descr',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='serie',
            name='descr',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='typecover',
            name='descr',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='descr',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
