# Generated by Django 2.2.5 on 2019-10-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refers', '0011_auto_20191018_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='descr',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
