# Generated by Django 2.2.5 on 2019-10-19 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20191016_1958'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_in_carts', to='books.Book', verbose_name='Книга')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='cart.Cart', verbose_name='Корзина')),
            ],
        ),
    ]
