# Generated by Django 2.2.5 on 2019-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20191019_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, BYN'),
        ),
    ]
