# Generated by Django 2.2.5 on 2019-10-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default='', verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
