# Generated by Django 2.2.5 on 2019-10-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=500, verbose_name='Адрес доставки'),
        ),
    ]
