# Generated by Django 2.2.5 on 2019-10-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191028_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(default='+37529', max_length=50, verbose_name='Мобильный телефон'),
            preserve_default=False,
        ),
    ]
