# Generated by Django 2.2.5 on 2019-10-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО получателя'),
        ),
    ]
