# Generated by Django 2.2.5 on 2019-10-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительные комментарии'),
        ),
    ]
