# Generated by Django 2.2.5 on 2019-11-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20191102_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=50, verbose_name='Способ доставки'),
            preserve_default=False,
        ),
    ]
