# Generated by Django 2.2.5 on 2019-11-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_profile',
        ),
    ]
