# Generated by Django 2.2.5 on 2019-11-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], max_length=50, verbose_name='Способ доставки:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Дополнительные комментарии:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=500, verbose_name='Адрес доставки:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(max_length=50, verbose_name='Мобильный телефон:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО получателя:'),
        ),
    ]
