# Generated by Django 2.2.5 on 2019-11-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20191105_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='e_mail',
            field=models.EmailField(default='bookstore.manager@yandex.ru', max_length=254),
            preserve_default=False,
        ),
    ]
