# Generated by Django 2.2.5 on 2019-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='e_mail',
            field=models.EmailField(max_length=254, verbose_name='E-mail:'),
        ),
    ]
